export const translations = {
  en: {
    back: "← Back",
    title: "Application Details",
     id: "ID",
  name: "Name",
  address: "Address",
  status: "Status",
  eligibility: "Eligibility",
    documents: "Uploaded Documents",
    checklist: "Verification Checklist",
    decision: "Final Decision",
    approve: "Approve",
    reject: "Reject",
    save: "Save Verification",
    comment: "Comment",
    select: "Select",
    noDocs: "No documents uploaded",
    fillAll: "Please complete all verification fields",
    successSave: "Verification saved successfully",
    errorSave: "Failed to save verification",
    connectionError: "Server connection failed",
      land: "Land",
  marital: "Marital",
  kebele: "Kebele",
  fayida: "Fayida",
  verified: "Verified",
    notVerified: "Not Verified",
     signature: "Signature",
  fayida_id_doc: "Fayida ID",
  kebele_id_doc: "Kebele ID"
  },

  am: {
    back: "← ተመለስ",
    title: "ማመልከቻ ዝርዝር",
      id: "መለያ",
  name: "ስም",
  address: "አድራሻ",
  status: "ሁኔታ",
  eligibility: "ብቁነት",
    documents: "የተጫኑ ሰነዶች",
    checklist: "የማረጋገጫ ዝርዝር",
    decision: "የመጨረሻ ውሳኔ",
    approve: "አጽድቅ",
    reject: "አስወግድ",
    save: "ማረጋገጫን አስቀምጥ",
    comment: "አስተያየት",
    select: "ይምረጡ",
    noDocs: "ምንም ሰነዶች አልተጫኑም",
    fillAll: "እባክዎ ሁሉንም ማረጋገጫዎች ይሙሉ",
    successSave: "በተሳካ ሁኔታ ተቀምጧል",
    errorSave: "ማስቀመጥ አልተሳካም",
    connectionError: "ከሰርቨር ጋር መገናኘት አልተቻለም",
     land: "መሬት",
  marital: "የጋብቻ ",
  kebele: "ቀበሌ",
  fayida: "ፋይዳ",
   verified: "ተረጋግጧል",
    notVerified: "አልተረጋገጠም",
    signature: "ፊርማ",
  fayida_id_doc: "የፋይዳ መታወቂያ",
  kebele_id_doc: "የቀበሌ መታወቂያ"
  }
};